# Variables for GNU make, files and targets

PDF_PATH=$(BASEDIR)/pdf
pdf_files=$(patsubst %, $(PDF_PATH)/%, $(pdf))
html_files=$(html)
markdown_files=$(patsubst %.pdf, %.md, $(pdf))

# Configuration

css=$(BASEDIR)/templates/pandoc-cv.css
context_style=$(BASEDIR)/templates/context.tex
latex_template=$(BASEDIR)/templates/latex-template.tex
latex_header=$(BASEDIR)/templates/latex-header.tex
pandoc_yaml=$(BASEDIR)/templates/pandoc.yaml
data=$(BASEDIR)/data/cv.json
